site:
  title: connectome-fs Docs
  start_page: connectome-fs::index.adoc
  url: https://connectome-fs.github.io/docs
  keys:
    header_logo: logo.svg
    site_home_url: https://connectome-fs.github.io/
    site_home_label: connectome-fs home
    header_doc_title: connectome-fs Docs
antora:
  extensions:
    - "@antora/lunr-extension"
    - '@antora-supplemental/build-stack'
content:
  sources:
    - url: https://github.com/connectome-fs/connectome-fs.git
      branches: main
      start_path: docs
ui:
  bundle:
    url: https://github.com/antora-supplemental/valentus-theme/releases/download/v2/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  attributes:
    stem: latexmath
urls:
  html_extension_style: indexify
output:
  dir: public/docs
